apiVersion: v1
kind: Namespace
metadata:
  name: wsfw
  labels:
    name: wsfw
    environment: production
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
